name: Java CI with Maven on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven

      - name: test gh
        run: |
          gh repo view
#          gh status
#          gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
