name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn package

    - name: Extract Maven project version
      run: echo VERSION_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_ENV

    - name: Create Release
      run: |
        gh release create v${{ env.VERSION_NAME }}
        echo UPLOAD_URL=$(gh release view v${{ env.VERSION_NAME }} --json uploadUrl --jq '.uploadUrl') >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload jar to Release
      run: gh release upload v${{ env.VERSION_NAME }} ./target/pinger-${{ env.VERSION_NAME }}.jar
#      env:
#        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
